M48
; DRILL file {KiCad 7.0.6} date Tue Oct  8 11:47:15 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-08T11:47:15-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0469
%
G90
G05
T1
X5.185Y-2.01
X5.185Y-2.41
T2
X5.18Y-2.635
X5.18Y-2.735
T3
X4.655Y-2.785
X4.755Y-2.785
X4.855Y-2.785
X4.955Y-2.785
T4
X4.655Y-1.975
X4.755Y-1.975
X4.855Y-1.975
X4.955Y-1.975
T0
M30
